<?php

add_action( 'acf/include_fields', function() {
    if ( ! function_exists( 'acf_add_local_field_group' ) ) {
        return;
    }

    // Press Page Options
    acf_add_local_field_group(array(
        'key' => 'group_5d7905cb433a6',
        'title' => 'Press Options',
        'fields' => array(
            array (
                'key' => 'field_5d5bkk324b028',
                'label' => 'Title font size',
                'name' => 'press_title_font_size',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array (
                    'l' => 'Big',
                    'm' => 'Regular',
                    's' => 'Small'
                ),
                'default_value' => array (
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5d7905d3c7cef',
                'label' => 'Intro',
                'name' => 'press_intro',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'basic',
                'media_upload' => 0,
                'delay' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'videos',
                ),
            ), array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'games',
                ),
            ), array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'updates',
                ),
            ), array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    // Options for standard posts
    acf_add_local_field_group(array (
        'key' => 'group_5d9f1b1b8985b_1',
        'title' => 'Associated Game',
        'fields' => array (
            array (
                'key' => 'field_5d9f1b2402b91',
                'label' => 'Select a game',
                'name' => 'game',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array (
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array (
                    'none' => 'None',
                    'berlin' => 'Berlin',
                    'duesseldorf' => 'Düsseldorf',
                    'mainz' => 'Mainz',
                ),
                'default_value' => array (
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'ajax' => 0,
                'return_format' => 'value',
                'placeholder' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    acf_add_local_field_group(array (
        'key' => 'post_teaser',
        'title' => 'Teaser',
        'fields' => array (
            array (
                'key' => 'post_teaser_image',
                'label' => 'Teaser Image',
                'name' => 'post_teaser_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'games',
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'updates',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ));

    // Options for game specifications
    acf_add_local_field_group(array (
        'key' => 'group_5d9f1b1b8985b_2',
        'title' => 'Game Specifications',
        'fields' => array (
            array(
                'key'               => 'field_5d9f1b2402b91_2_1',
                'label'             => 'Column Headers',
                'name'              => 'column_headers',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_5d9f1b2402b91_2_2',
                        'label'             => 'Text',
                        'name'              => 'text',
                        'type'              => 'text'
                    )
                ),
            ),
            array(
                'key'               => 'field_5d9f1b2402b91_2_3',
                'label'             => 'Rows',
                'name'              => 'rows',
                'type'              => 'repeater',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_5d9f1b2402b91_2_4',
                        'label'             => 'Row',
                        'name'              => 'row',
                        'type'              => 'repeater',
                        'instructions'      => '',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'collapsed'         => '',
                        'min'               => 0,
                        'max'               => 0,
                        'layout'            => 'row',
                        'button_label'      => '',
                        'sub_fields'        => array(
                            array(
                                'key'               => 'field_5d9f1b2402b91_2_5',
                                'label'             => 'Text',
                                'name'              => 'text',
                                'type'              => 'text'
                            )
                        ),
                    ),
                ),
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'games',
                ),
            ),
        ),
        'menu_order' => 0,
        'active' => 1,
    ));

    // Options for game specifications
    acf_add_local_field_group(array (
        'key' => 'group_5d9f1b1b8985b_3',
        'title' => 'Video Configuration',
        'fields' => array (
            array(
                'key'               => 'field_5d9f1b2402b91_3_1',
                'label'             => 'Video is Live?',
                'name'              => 'video_is_live',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
            ),
            array(
                'key'               => 'field_5d9f1b2402b91_3_2',
                'label'             => 'Stream Embed',
                'name'              => 'embed',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
            ),
            array(
                'key'               => 'field_5d9f1b2402b91_3_4',
                'label'             => 'Location',
                'name'              => 'location',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
            ),
            array(
                'key'               => 'field_5d9f1b2402b91_3_5',
                'label'             => 'Date Start (DD.MM.YYYY 00:00)',
                'name'              => 'date_from',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
            ),
            array(
                'key'               => 'field_5d9f1b2402b91_3_6',
                'label'             => 'Date End (DD.MM.YYYY 00:00)',
                'name'              => 'date_end',
                'type'              => 'text',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'videos',
                ),
            ),
        ),
        'menu_order' => 0,
        'active' => 1,
    ));

    // Global Settings
    acf_add_local_field_group( array(
        'key' => 'group_5eefd21b34e5d',
        'title' => 'Global Settings',
        'fields' => array(
            array(
                'key' => 'field_5eefd24cab11b',
                'label' => 'Legal Copy',
                'name' => 'legal_copy',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '3',
                'placeholder' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'footer_buy_buttons',
                'label' => 'Buy Buttons',
                'name' => 'footer_buy_buttons',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'footer_buy_buttons_title',
                        'label' => 'Text',
                        'name' => 'footer_buy_buttons_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'footer_buy_buttons_link',
                        'label' => 'Link',
                        'name' => 'footer_buy_buttons_link',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_654a68665a57f',
                'label' => 'Read More',
                'name' => 'read_more',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_456h78j8904fg',
                'label' => 'Wishlist URL',
                'name' => 'wishlist_url',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );

    // Social Channels
    acf_add_local_field_group( array(
        'key' => 'group_social_channels',
        'title' => 'Social Channels',
        'fields' => array(
            array(
                'key' => 'social_channels_overline',
                'label' => 'Overline',
                'name' => 'social_channels_overline',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'social_channels_headline',
                'label' => 'Headline',
                'name' => 'social_channels_headline',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'social_channels_text',
                'label' => 'Text',
                'name' => 'social_channels_text',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '3',
                'placeholder' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'social_channels_buttons',
                'label' => 'Buttons',
                'name' => 'social_channels_buttons',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'social_channels_button_title',
                        'label' => 'Text',
                        'name' => 'social_channels_button_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'social_channels_button_link',
                        'label' => 'Link',
                        'name' => 'social_channels_button_link',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'social_channels_button_icon',
                        'label' => 'Icon',
                        'name' => 'social_channels_button_icon',
                        'aria-label' => '',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'url',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                        'preview_size' => 'thumbnail',
                    ),
                    array(
                        'key' => 'component_button_show_teaser',
                        'label' => 'Show in teaser?',
                        'name' => 'component_button_show_teaser',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 1,
                        'ui' => 1,
                        'ui_on_text' => _x('Yes', 'post type', 'psl-custom'),
                        'ui_off_text' => _x('No', 'post type', 'psl-custom'),
                    ),
                    array(
                        'key' => 'component_button_show_footer',
                        'label' => 'Show in footer?',
                        'name' => 'component_button_show_footer',
                        'type' => 'true_false',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => '',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => _x('Yes', 'post type', 'psl-custom'),
                        'ui_off_text' => _x('No', 'post type', 'psl-custom'),
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );

    // Scroll of Fame
    acf_add_local_field_group( array(
        'key' => 'page_scrolloffame',
        'title' => 'Scroll of Fame',
        'fields' => array(
            array(
                'key' => 'page_scrolloffame_trailer',
                'label' => 'Trailer',
                'name' => 'trailer',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'videos',
                ),
                'taxonomy' => '',
                'allow_null' => 1,
                'multiple' => 0,
                'return_format' => 'id',
                'ui' => 1,
                'bidirectional_target' => array(
                ),
            ),
            array(
                'key' => 'page_scrolloffame_intro',
                'label' => 'Intro Copy',
                'name' => 'intro_copy',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '3',
                'placeholder' => '',
                'new_lines' => 'br',
            ),
            array(
                'key' => 'page_scrolloffame_outro',
                'label' => 'Outro Copy',
                'name' => 'outro_copy',
                'aria-label' => '',
                'type' => 'textarea',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'rows' => '3',
                'placeholder' => '',
                'new_lines' => 'br',
            ),
            array(
                'key'               => 'page_scrolloffame_backlink',
                'label'             => 'Backlink URL',
                'name'              => 'backlink',
                'type'              => 'text',
                'instructions'      => 'Leave empty to use home link from Settings->General.',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'row',
                'button_label'      => '',
            ),
            array(
                'key' => 'page_scrolloffame_comments',
                'label' => 'Comments CSV',
                'name' => 'comments',
                'aria-label' => '',
                'type' => 'file',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => 'csv',
            ),
            array(
                'key' => 'page_scrolloffame_comments_skip_rows',
                'label' => 'Comments CSV Skip Rows',
                'name' => 'comments_skip_rows',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 1,
                'min' => 0,
                'max' => '',
                'placeholder' => '',
                'step' => 1,
                'prepend' => '',
                'append' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'template-parts/scroll-of-fame.php',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'the_content',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );





    // Poll fields
    acf_add_local_field_group( array(
        'key' => 'group_67443b05db5db',
        'title' => __( 'Poll Fields', '123' ),
        'fields' => array(
            array(
                'key' => 'field_6745a5608c6a9',
                'label' => __( 'Active', '123' ),
                'name' => 'poll_active',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 1,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ),
            array(
                'key' => 'field_674481c5d2d35',
                'label' => __( 'Feature Image', '123' ),
                'name' => 'poll_feature_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_67443b065ccb6',
                'label' => __( 'Poll Question', '123' ),
                'name' => 'poll_question',
                'aria-label' => '',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'maxlength' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ),
            array(
                'key' => 'field_6745ad5892f4b',
                'label' => __( 'Poll Choice Type', '123' ),
                'name' => 'poll_type',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'single' => __( 'Single Choice', '123' ),
                    'multiple' => __( 'Multiple Choice', '123' ),
                ),
                'default_value' => 'single',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'horizontal',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_67443b485ccb8',
                'label' => __( 'Poll Choices', '123' ),
                'name' => 'poll_items',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'table',
                'pagination' => 0,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => __( 'Add Choice', '123' ),
                'rows_per_page' => 20,
                'sub_fields' => array(
                    array(
                        'key' => 'field_67443b9cc1676',
                        'label' => __( 'Choice Text', '123' ),
                        'name' => 'choice_text',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_67443b485ccb8',
                    ),
                    array(
                        'key' => 'field_67443bc1c1677',
                        'label' => __( 'Vote Count', '123' ),
                        'name' => 'vote_count',
                        'aria-label' => '',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 0,
                        'min' => '',
                        'max' => '',
                        'placeholder' => '',
                        'step' => '',
                        'prepend' => '',
                        'append' => '',
                        'readonly' => true,
                        'parent_repeater' => 'field_67443b485ccb8',
                    ),
                ),
            ),
            array(
                'key' => 'field_67443bde7be05',
                'label' => __( 'Total Votes', '123' ),
                'name' => 'total_votes',
                'aria-label' => '',
                'type' => 'number',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => 0,
                'min' => '',
                'max' => '',
                'placeholder' => '',
                'step' => '',
                'prepend' => '',
                'append' => '',
                'readonly' => true,
            ),
            array(
                'key' => 'field_6744564887e45',
                'label' => __( 'Show Users', '123' ),
                'name' => 'show_users',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
                'ui' => 1,
            ),
            array(
                'key' => 'field_67443c007be06',
                'label' => __( 'Voted Users', '123' ),
                'name' => 'voted_users',
                'aria-label' => '',
                'type' => 'repeater',
                'instructions' => __( 'You can also add a user ID and email to block them from voting on this poll', '123' ),
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_6744564887e45',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'pagination' => 1,
                'rows_per_page' => 20,
                'min' => 0,
                'max' => 0,
                'collapsed' => '',
                'button_label' => __( 'Add User', '123' ),
                'sub_fields' => array(
                    array(
                        'key' => 'field_67443c277be07',
                        'label' => __( 'User ID', '123' ),
                        'name' => 'user_id',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_67443c007be06',
                    ),
                    array(
                        'key' => 'field_674456c1df0be',
                        'label' => __( 'User email', '123' ),
                        'name' => 'user_email',
                        'aria-label' => '',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'parent_repeater' => 'field_67443c007be06',
                    ),
                ),
            ),
            array(
                'key' => 'field_67443c46ec81e',
                'label' => __( 'Poll Start Date', '123' ),
                'name' => 'poll_start_date',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'Y-m-d',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_67443c63ec81f',
                'label' => __( 'Poll End Date', '123' ),
                'name' => 'poll_end_date',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'Y-m-d',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_6745f334d1f65',
                'label' => __( 'Poll Show Until Date', '123' ),
                'name' => 'poll_show_until_date',
                'aria-label' => '',
                'type' => 'date_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '33',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y',
                'return_format' => 'Y-m-d',
                'first_day' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'polls',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'permalink',
            1 => 'the_content',
            2 => 'excerpt',
            3 => 'discussion',
            4 => 'comments',
            5 => 'revisions',
            6 => 'slug',
            7 => 'author',
            8 => 'format',
            9 => 'page_attributes',
            10 => 'featured_image',
            11 => 'categories',
            12 => 'tags',
            13 => 'send-trackbacks',
        ),
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );
    

    // Associated Poll
    acf_add_local_field_group( array(
        'key' => 'group_6746cd8be3a7e',
        'title' => __( 'Associated Poll', '123' ),
        'fields' => array(
            array(
                'key' => 'field_6746cd8c15cf0',
                'label' => __( 'Selected Poll', '123' ),
                'name' => 'selected_poll',
                'aria-label' => '',
                'type' => 'post_object',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'polls',
                ),
                'post_status' => '',
                'taxonomy' => '',
                'return_format' => 'id',
                'multiple' => 0,
                'allow_null' => 0,
                'bidirectional' => 0,
                'ui' => 1,
                'bidirectional_target' => array(
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ) );


    
} );







